baseurl = "https://barthpaleologue.github.io/Blog"
DefaultContentLanguage = "en"
title = "Barth Cave"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
#pygmentsStyle = "trac"
#pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

staticDir = ["static"]

[Params]
  homeTitle = "Barth Cave" # Set a different text for the header on the home page
  subtitle = "Articles where I explain crazy computer graphics stuff"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  #useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Barthélemy Paléologue"
  website = "barth.paleologue.fr"
  email = "barth@paleologue.fr"
  github = "BarthPaleologue"
  #gitlab = "username"
  #linkedin = "username"
  #stackoverflow = "users/XXXXXXX/username"
  youtube = "channel/UCJIpGVX-iL59o-Rpxom2_aA"
  #mastodon = "url"
  #kaggle = "username"
  #slack = "username"
  medium = "barth_29567"
  
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3